### ISSUE TITLE
Improve UI for shadows box

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#277] opened 2019-08-24 17:03 UTC
The old shadows list was quite clear. If you had multiple shadows, all would be immediately visible in the list.
![Screenshot from 2019-08-24 18-56-14](https://user-images.githubusercontent.com/668724/63640509-841c6b00-c6a1-11e9-9a8c-9f7a0e0db53b.png)

The new shadows box feels quite cluttered. One needs to find the shadows from a drop down. The text alignment does not look good, and with the new search-replace integrated there is more features yes, but the look is a bit messy.
![Screenshot from 2019-08-24 18-57-55](https://user-images.githubusercontent.com/668724/63640523-b5953680-c6a1-11e9-8cf9-16fdcee67ce6.png)

The functionality itself is good, but some rearrangement and UI design would be needed here to make the user experience smooth.

**Comment by JoosuaKoskinen** [comment] 2019-08-26 16:29
It seems that there's some CSS problems in the screenshot you posted. But I agree, it could look better. Due to postbox working only with boxes with 25% of width, there's not much room for design. The old 100% table was bit of a hack which can't be used with the new Seravo-toolbox design. That's why the page now uses mails-page style dropdown. New ideas for shadows-page are desired.

Which site is that screenshot from and can you still reproduce the problems? 

![shadows](https://user-images.githubusercontent.com/42264063/63706009-16a24300-c837-11e9-92d5-c06fa9b769f9.png)

**Comment by ottok** [comment] 2020-06-12 14:19
I wrote now a help page about this since there was not docs on it so far: https://help.seravo.fi/article/358-varjosivusto

Still I think the UI is ugly. Also from a novice user point of view the translation is clumsy and some parts (such as the shadow comment) are not translated at all (and unfortunately cannot directly be, since it is a string from the info field of the shadow and not Seravo Plugin.

**Comment by ottok** [comment] 2020-06-12 14:20
@nuuttitoivola @elguitar @JoosuaKoskinen This issue needs an status update perhaps?

**Comment by elguitar** [comment] 2020-07-20 07:26
Closed via https://github.com/Seravo/seravo-plugin/commit/959083f9d47e63e4b732c5886eb8ad16f32368dd

**Closed by elguitar** 2020-07-20 07:26 UTC
Labels: enhancement
