### ISSUE TITLE
Invalid HTML in CheckPHPVersion admin_notice

### ISSUE THREAD

**Issue by TeemuSuoranta** [Seravo/seravo-plugin#260] opened 2019-07-05 08:06 UTC
Version: 1.9.9

The admin_notice for CheckPHPVersion returns invalid HTML:
```
<div class="notice notice-info">
      <p>
      PHP-versio 7.3 on saatavilla mutta ei käytössä. Kehittäjät haluavat todennäköisesti <a href="tools.php?page=updates_page">päivittää uusimpaan</a> PHP-versioon paremman suorituskyvyn ja uusien ominaisuuksien takia. Lue lisää <a target="_blank" href="https://help.seravo.com/fi/knowledgebase/13/docs/1      </p>
      </div>
```

This doesn't completely break anything as browsers will still render it to some degree. Visually the admin_notice is just huge (on Mac Chrome) when the markup is broken like this.

Not sure why it's broken. Probably the Finnish translation is somehow broken and it might be a good idea to break that string down to multiple strings and avoid " marks in translation files.

**Comment by JoosuaKoskinen** [comment] 2019-07-10 06:50
Couldn't reproduce this in 1.9.10, nor in 1.9.9. I agree that the paragraph is a bit long but I see no reason for it to cut in the middle of the link.

In the snippet it cuts at 299th character. Could it maybe be something site specific?

**Comment by TeemuSuoranta** [comment] 2019-07-10 07:01
I've seen it on multiple production and local sites.

For example on setup:
PHP v7.2.16
WP 5.2.2
Seravo plugin 1.9.9.

Doesn't cause anything to PHP error log but the markup is similarly broken. If I change my language to English, markup won't break but with Finnish it does.

If you cannot reproduce the problem I can give you a few sites that affected via email.

**Comment by JoosuaKoskinen** [comment] 2019-07-10 08:11
Tried with exactly the same versions, still works fine:
```
<div class="notice notice-info">
      <p>
      PHP-versio 7.3 on saatavilla mutta ei käytössä. Kehittäjät haluavat todennäköisesti <a href="tools.php?page=updates_page">päivittää uusimpaan</a> PHP-versioon paremman suorituskyvyn ja uusien ominaisuuksien takia. Lue lisää <a target="_blank" href="https://help.seravo.com/fi/knowledgebase/13/docs/107-uusimpaan-php-versioon-siirtyminen">PHP-versiopäivityksistä</a>.      </p>
      </div>
```

Example sites would be helpful. Could you please email a couple to wordpress@seravo.fi or joosua@seravo.fi.

**Comment by TeemuSuoranta** [comment] 2019-07-10 08:20
Sure thing. I sent you a couple.

**Comment by JoosuaKoskinen** [comment] 2019-07-10 13:30
Seems like an issue with a common plugin between the given sites. Sent more info via email because of a sites specific problem.

**Comment by TeemuSuoranta** [comment] 2019-07-10 14:06
So for the record, the affected sites seem to have mu-plugin Dynamic MO Loader (https://github.com/aucor/dynamic-mo-loader) in common that for whatever reason breaks this one string from .mo file. I have never seen dynamic-mo-loader do this kind of thing so I will look into it.

Dynamic MO Loader changes the native way that WordPress handles translations by caching them and getting them dynamically. The plugin has 16k downloads in composer and has been mentioned by Otto in a past optimization presentation (https://www.slideshare.net/ottokekalainen/improving-wordpress-performance-with-xdebug-and-php-profiling)

I'll gladly take any help to track down the bug in Dynamic MO Loader but I understand that we are out of scope here. I'll use the .po/.mo from this plugin as reference and try to find the issue. Are you using the `wp-pomo-compile` (https://seravo.com/docs/get-started/available-commands/) to generate these files?

**Comment by JoosuaKoskinen** [comment] 2019-07-11 11:29
It definitely would be good to track the issue down. Please tell us if there's something that should be fixed on Seravo Plugin side.

I think we are using `wp-pomo-compile`, yes. Or `msgfmt` which it's a wrapper for.

**Comment by ottok** [comment] 2019-07-12 06:08
The `.mo` files in the Seravo Plugin are generated by Poedit when the person updating the translation is saving the translation.

**Comment by ottok** [comment] 2019-07-12 06:10
Note that I updated the translations a week ago, so updating the plugin to latest development version with `wp-seravo-plugin --dev` might fix the issue.

**Comment by TeemuSuoranta** [comment] 2019-07-29 13:49
There's been progress in this issue from our part. Firstly, yes, this is a bug in Dynamic MO Loader and not in Seravo Plugin.

Now, the reason why this bug exists is most strange. Basically Dynamic MO Loader checks if the string has 0 in it and if it has, the string will be concatenated to that point.

Timeline:
- Check was introduced in WP Performance Pack to check if string is plurar or not(?) https://github.com/wp-plugins/wp-performance-pack/commit/282a9e598bbfc64919e7426d0611893b88e3f178#diff-5b897474a1fd5b8a448e652b5c787520L179
- Int 0 caused warnings in PHP7.3 and was turned into string '0' https://github.com/aucor/dynamic-mo-loader/commit/5bda42e6af9da58601377e2c9e60b9b4d6d376d0
- Now this check was removed: https://github.com/aucor/dynamic-mo-loader/commit/ed2f9fb3e0b830502fe6d402b9c6086982d3da5f#diff-3869192b3dc106266c4b312dbcfc8568L499

We are still testing this at the moment but will probably make a release soon that will fix this. I find it really strange that this bug has not been reported before.

**Comment by JoosuaKoskinen** [comment] 2019-08-17 10:10
Great that this got figured out!

Closing this now as no need to do anything with Seravo Plugin.

**Closed by JoosuaKoskinen** 2019-08-17 10:10 UTC
Labels: bug
