### ISSUE TITLE
Show scandinavian characters properly in shadow indicator message

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#175] opened 2018-08-29 07:15 UTC
Seems that scandinavian characters are not correctly showing at e.g. the shadow wp-palvelu-26d56e:

![screen shot 2018-08-29 at 10 11 52](https://user-images.githubusercontent.com/24781811/44771611-26c80980-ab74-11e8-9d7c-6b2ba631426f.png)

According to swd, it should read
```
==== wp-palvelu_26d56e ====
...
info: WP-palvelu.fi:n UAT-ympäristö
...
```
, but the "ö" character is not correctly shown. This is probably not very urgent, but it would be nice for the indicator to look professional if a customer requests for a custom shadow message other than the defaultly used "Staging".

**Comment by mikkoaf** [comment] 2019-01-25 08:01
I tried replicating this issue, modifying my shadow instance info to "Ääkköset"
![image](https://user-images.githubusercontent.com/16817737/51732700-b9b79200-2087-11e9-9fb6-55d35f9882a2.png)

Currently `WP_ENV_COMMENT` is not available and staging environment name is not shown to the user in the red bar.
![image](https://user-images.githubusercontent.com/16817737/51732506-3433e200-2087-11e9-9a7b-aa2bc75934a5.png)
https://github.com/Seravo/seravo-plugin/blob/5511340dd7853f8081895e7f34b7a0c759691804/modules/instance-switcher.php#L172

**Comment by JoosuaKoskinen** [comment] 2019-06-01 12:01
Tried this with "Ääkköset" shadow name. WP_ENV_COMMENT was included and Scandinavian characters still seem to be an issue.

![Shadow scandinavian characters](https://user-images.githubusercontent.com/42264063/58748221-f2c0a280-847d-11e9-952e-0fba84922fc1.png)

**Comment by JoosuaKoskinen** [comment] 2019-06-03 06:26
Doesn't seem like a plugin side issue. I got the following from wp-list-env:

WP_ENV_COMMENT: kkset

**Comment by elguitar** [comment] 2019-06-05 13:28
I can confirm what @JoosuaKoskinen suggested.
This is not a plugin issue, since there are scandics missing from the ENVs and they are not lost in the plugin.

Closing and opening elsewhere

**Closed by elguitar** 2019-06-05 13:28 UTC
