### ISSUE TITLE
Refactor current codebase to be more uniform in architecture 

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#141] opened 2018-07-03 07:39 UTC
Currently some of the features provided by the Seravo-plugin are written so that the functionality and content creation are separated from the style sheets page layouts and others are not.

In order to make further development easier, pages like Reports, Tests and Domains need to be refactored so that form and function are separated.

**Comment by ottok** [comment] 2021-01-22 09:48
We don't have pages "Reports, Tests and Domains" anymore, and there is no concrete suggestion on the refactoring here, so the issue is not worth keeping open anymore. Closing.

**Closed by ottok** 2021-01-22 09:48 UTC
Labels: codebase
